# permissions for end users to edit chains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chain-editor-role
rules:
- apiGroups:
  - cloud.io.cloud-operator
  resources:
  - chains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.io.cloud-operator
  resources:
  - chains/status
  verbs:
  - get
