# permissions for end users to view chains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chain-viewer-role
rules:
- apiGroups:
  - cloud.io.cloud-operator
  resources:
  - chains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.io.cloud-operator
  resources:
  - chains/status
  verbs:
  - get
