---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cloud.io.cloud-operator
  resources:
  - chains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.io.cloud-operator
  resources:
  - chains/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.io.cloud-operator
  resources:
  - chains/status
  verbs:
  - get
  - patch
  - update
