apiVersion: v1
kind: Service
metadata:
  name: chain-service
  namespace: cloud-chain
spec:
  selector:
    app: chain-service
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
  type: NodePort